server:
  host: 0.0.0.0
  port: 4443
  options:
    connections:
      routes:
        cors: true


swag:
  info:
    title: Easy gifts for free

mongodb:
  host: 0.0.0.0
  port: 27017
  db: angulaaaaaargh
mailjet:
  key:
    public: f9dea911c99fa19c24b0d3d5a45da674
    private: 6f054dfc49b5926107e4bd37d5b72c60