server:
  host: 0.0.0.0
  port: 4443

swag:
  info:
    title: Easy gifts for free
mongodb:
  host: 172.17.0.2
  port: 27017
  db: angulaaaaaargh
mail:
  host: smtp.gmail.com
  port: 465
  secure: true
  auth: {
    user: ezgifts54@gmail.com,
    pass: MotDePasse!54
  }
